/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tarea01pbf;

import java.util.Date;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author pacob
 */
public class JDialogPrestamo extends javax.swing.JDialog {

    /**
     * Creates new form JDialogPrestamo
     */
    public JDialogPrestamo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEncuad = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomApell = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNumTelef = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldISBN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldAutor = new javax.swing.JTextField();
        jComboBoxEditoriales = new javax.swing.JComboBox<>();
        jCheckBoxTab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxTab11 = new javax.swing.JCheckBox();
        jCheckBoxTab12 = new javax.swing.JCheckBox();
        jCheckBoxTab13 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxTab21 = new javax.swing.JCheckBox();
        jCheckBoxTab22 = new javax.swing.JCheckBox();
        jCheckBoxTab23 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jCheckBoxTab31 = new javax.swing.JCheckBox();
        jCheckBoxTab32 = new javax.swing.JCheckBox();
        jCheckBoxTab33 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jCheckBoxTab41 = new javax.swing.JCheckBox();
        jCheckBoxTab42 = new javax.swing.JCheckBox();
        jCheckBoxTab43 = new javax.swing.JCheckBox();
        jSpinnerFechaPrestamo = new javax.swing.JSpinner();
        jSpinnerFechaDevolucion = new javax.swing.JSpinner();
        jButtonSalir = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jRadioButtonRustica = new javax.swing.JRadioButton();
        jRadioButtonTapaDura = new javax.swing.JRadioButton();
        jRadioButtonPiel = new javax.swing.JRadioButton();
        jPanelPersonalizado2 = new componentevisualpersonalizado.JPanelPersonalizado();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nombre y Apellidos:");

        jTextFieldNomApell.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldNomApell.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldNomApell.setForeground(new java.awt.Color(153, 153, 255));
        jTextFieldNomApell.setToolTipText("Inserte su nombre y apellidos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("DNI:");

        jTextFieldDNI.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldDNI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldDNI.setForeground(new java.awt.Color(153, 153, 255));
        jTextFieldDNI.setToolTipText("Inserte su DNI");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Teléfono de contacto:");

        jTextFieldNumTelef.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldNumTelef.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldNumTelef.setForeground(new java.awt.Color(153, 153, 255));
        jTextFieldNumTelef.setToolTipText("Inserte su nº de teléfono");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("ISBN:");

        jTextFieldISBN.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldISBN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldISBN.setForeground(new java.awt.Color(153, 153, 255));
        jTextFieldISBN.setToolTipText("Introduzca aqui el ISBN del libro");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Título del libro:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Autor del Libro:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Editorial:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tipo de encuadernación:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Materias:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Fecha préstamo Libro:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Fecha devolución Libro:");

        jTextFieldTitulo.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldTitulo.setForeground(new java.awt.Color(153, 153, 255));
        jTextFieldTitulo.setToolTipText("Inserte aqui el titulo del libro");

        jTextFieldAutor.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldAutor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldAutor.setForeground(new java.awt.Color(153, 153, 255));
        jTextFieldAutor.setToolTipText("Inserte aquí la editorial del libro");

        jComboBoxEditoriales.setBackground(new java.awt.Color(204, 255, 255));
        jComboBoxEditoriales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBoxEditoriales.setForeground(new java.awt.Color(153, 153, 255));
        jComboBoxEditoriales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urano Ediciones", "Círculo Rojo", "Vicens Vives", "Altamar" }));
        jComboBoxEditoriales.setToolTipText("Indique aquí la editorial que quiere usar");
        jComboBoxEditoriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEditorialesActionPerformed(evt);
            }
        });

        jCheckBoxTab.setBackground(new java.awt.Color(255, 153, 255));
        jCheckBoxTab.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTab.setToolTipText("");
        jCheckBoxTab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jCheckBoxTab11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxTab11.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTab11.setText("Analisis de alimentos");

        jCheckBoxTab12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxTab12.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTab12.setText("Industria Alimentaria");

        jCheckBoxTab13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxTab13.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTab13.setText("Nutricion y Dietetica");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxTab11)
                    .addComponent(jCheckBoxTab12)
                    .addComponent(jCheckBoxTab13))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxTab11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTab12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTab13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCheckBoxTab.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setForeground(new java.awt.Color(255, 102, 255));

        jCheckBoxTab21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxTab21.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTab21.setText("Neurologia");

        jCheckBoxTab22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxTab22.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTab22.setText("Patologia");

        jCheckBoxTab23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxTab23.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTab23.setText("Medicina General");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxTab21)
                    .addComponent(jCheckBoxTab22)
                    .addComponent(jCheckBoxTab23))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxTab21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTab22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTab23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCheckBoxTab.addTab("tab2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));

        jCheckBoxTab31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxTab31.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTab31.setText("Derecho Privado");

        jCheckBoxTab32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxTab32.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTab32.setText("Derecho Publico");

        jCheckBoxTab33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxTab33.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTab33.setText("Derecho Militar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxTab31)
                    .addComponent(jCheckBoxTab32)
                    .addComponent(jCheckBoxTab33))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxTab31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTab32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTab33)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jCheckBoxTab.addTab("tab3", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 204, 255));

        jCheckBoxTab41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxTab41.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTab41.setText("Flamenco");

        jCheckBoxTab42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxTab42.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTab42.setText("Musica Clasica");

        jCheckBoxTab43.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxTab43.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTab43.setText("Teoria e Historia de la Musica");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxTab41, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxTab42)
                    .addComponent(jCheckBoxTab43))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxTab41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTab42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTab43)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jCheckBoxTab.addTab("tab4", jPanel5);

        jSpinnerFechaPrestamo.setModel(new javax.swing.SpinnerDateModel());

        jSpinnerFechaDevolucion.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1727965920000L), null, null, java.util.Calendar.DAY_OF_MONTH));

        jButtonSalir.setBackground(new java.awt.Color(102, 0, 204));
        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonGuardar.setBackground(new java.awt.Color(102, 0, 204));
        jButtonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar Registro");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        buttonGroupEncuad.add(jRadioButtonRustica);
        jRadioButtonRustica.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButtonRustica.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonRustica.setText("Rústica");
        jRadioButtonRustica.setToolTipText("Tipo de encuadernacion rustica");
        jRadioButtonRustica.setEnabled(false);

        buttonGroupEncuad.add(jRadioButtonTapaDura);
        jRadioButtonTapaDura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButtonTapaDura.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonTapaDura.setText("Tapa Dura");
        jRadioButtonTapaDura.setToolTipText("Tipo de encuadernacion de tapa dura");
        jRadioButtonTapaDura.setEnabled(false);

        buttonGroupEncuad.add(jRadioButtonPiel);
        jRadioButtonPiel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButtonPiel.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonPiel.setText("Piel");
        jRadioButtonPiel.setToolTipText("Tipo de encuadernacion de piel");
        jRadioButtonPiel.setEnabled(false);

        jPanelPersonalizado2.setBackground(new java.awt.Color(204, 204, 255));
        jPanelPersonalizado2.setToolTipText("Inserte aquí su correo electrónico");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomApell, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelPersonalizado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonRustica, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonTapaDura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonPiel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDNI))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumTelef))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldISBN))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTitulo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAutor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxEditoriales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerFechaDevolucion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerFechaPrestamo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxTab, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNomApell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPersonalizado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNumTelef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxEditoriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonRustica)
                    .addComponent(jRadioButtonTapaDura)
                    .addComponent(jRadioButtonPiel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jCheckBoxTab, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jSpinnerFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jSpinnerFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonSalir))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jCheckBoxTab.getAccessibleContext().setAccessibleName("Alimentación-Nutrición");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        Map<String, Object> datos = recogerDatos();
        
        System.out.println("------------------------------------");
        System.out.println("---------RESERVA CONFIRMADA---------");
        System.out.println("Nombre y Apellidos: " + datos.get("nombreApellidos"));
        System.out.println("Email: " + datos.get("email"));
        System.out.println("DNI: " + datos.get("dni"));
        System.out.println("Numero de telefono: " + datos.get("numeroTelef"));
        System.out.println("ISBN: " + datos.get("isbn"));
        System.out.println("Titulo del libro: " + datos.get("titulo"));
        System.out.println("Autor: " + datos.get("autor"));
        System.out.println("Editorial: " + datos.get("eleccionEditorial"));
        System.out.println("Encuadernacion: " + datos.get("eleccionEncuadernacion"));
        
        int contadorAdded = 0;
        System.out.print("Materias: ");
        List<String> materias = (List<String>) datos.get("materias"); // Obtener materias como lista
        if (materias != null && !materias.isEmpty()) {
            for (String materia : materias) {
                System.out.println(materia);
                contadorAdded++;
            }
        } else {
            System.out.println("Ninguna materia seleccionada");
        }

        System.out.println("\nNúmero de materias seleccionadas: " + contadorAdded);
        System.out.println("Fecha del préstamo: " + datos.get("fechaPrestamo"));
        System.out.println("Fecha de devolución: " + datos.get("fechaDevolucion"));
        System.out.println("------------------------------------");
        
        
        //Mostrar mensaje si se han guardado o no todos los datos
        if (datos.get("nombreApellidos") == null || datos.get("nombreApellidos").toString().trim().isEmpty() ||
        datos.get("email") == null || datos.get("email").toString().trim().isEmpty() ||
        datos.get("dni") == null || datos.get("dni").toString().trim().isEmpty() ||
        datos.get("numeroTelef") == null ||
        datos.get("isbn") == null ||
        datos.get("titulo") == null || datos.get("titulo").toString().trim().isEmpty() ||
        datos.get("autor") == null || datos.get("autor").toString().trim().isEmpty() ||
        datos.get("eleccionEditorial") == null || datos.get("eleccionEditorial").toString().trim().isEmpty() ||
        datos.get("fechaPrestamo") == null ||
        datos.get("fechaDevolucion") == null) {
        
        // Mostrar mensaje de advertencia
        JOptionPane.showMessageDialog(
                this, 
                "Por favor, complete todos los campos requeridos antes de guardar.", 
                "Datos incompletos", 
                JOptionPane.WARNING_MESSAGE
        );
        } else {
            // Mostrar mensaje de registro guardado
            JOptionPane.showMessageDialog(
                    this, 
                    "Registro guardado correctamente.", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jComboBoxEditorialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEditorialesActionPerformed
        String eleccionEditorial = String.valueOf(jComboBoxEditoriales.getSelectedItem());
        String eleccionEncuadernacion = "Por defecto";
        
        if ((eleccionEditorial.equals("Vicens Vives")) || (eleccionEditorial.equals("Altamar"))) {
            jRadioButtonRustica.setEnabled(true);
            jRadioButtonTapaDura.setEnabled(true);
            jRadioButtonPiel.setEnabled(true);
            if (jRadioButtonRustica.isSelected()) {
                eleccionEncuadernacion = jRadioButtonRustica.getText();
            } else if (jRadioButtonTapaDura.isSelected()) {
                eleccionEncuadernacion = jRadioButtonTapaDura.getText();
            } else if (jRadioButtonPiel.isSelected()) {
                eleccionEncuadernacion = jRadioButtonPiel.getText();
            }
        } else {
            jRadioButtonRustica.setEnabled(false);
            jRadioButtonTapaDura.setEnabled(false);
            jRadioButtonPiel.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxEditorialesActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        Map<String, Object> datosIntroducidos = recogerDatos();
        
        boolean hayDatos = false;

        // Verificar campos del cliente directamente
        if (datosIntroducidos.get("nombreApellidos") != null && 
            !datosIntroducidos.get("nombreApellidos").toString().trim().isEmpty()) {
            hayDatos = true;
        }
        if (datosIntroducidos.get("email") != null && 
            !datosIntroducidos.get("email").toString().trim().isEmpty()) {
            hayDatos = true;
        }
        if (datosIntroducidos.get("dni") != null && 
            !datosIntroducidos.get("dni").toString().trim().isEmpty()) {
            hayDatos = true;
        }
        if (datosIntroducidos.get("numeroTelef") != null) {
            hayDatos = true;
        }

        // Si hay datos introducidos, confirmar la salida
        if (hayDatos) {
            int confirmacion = JOptionPane.showConfirmDialog(
                    this,
                    "Se han introducido datos del cliente. ¿Realmente quiere salir?",
                    "Confirmar salida",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (confirmacion == JOptionPane.YES_OPTION) {
                this.dispose(); 
            }
        } else {
            this.dispose();
        }

    }//GEN-LAST:event_jButtonSalirActionPerformed

    public Map<String, Object> recogerDatos() {
        Map<String, Object> datosFormulario = new HashMap<>();

        datosFormulario.put("nombreApellidos", jTextFieldNomApell.getText());
        datosFormulario.put("email", jPanelPersonalizado2.getEmailText());
        datosFormulario.put("dni", jTextFieldDNI.getText());

        try {
            datosFormulario.put("numeroTelef", Integer.valueOf(jTextFieldNumTelef.getText()));
        } catch (NumberFormatException e) {
            datosFormulario.put("numeroTelef", null);
        }

        try {
            datosFormulario.put("isbn", Integer.valueOf(jTextFieldISBN.getText()));
        } catch (NumberFormatException e) {
            datosFormulario.put("isbn", null);
        }

        datosFormulario.put("titulo", jTextFieldTitulo.getText());
        datosFormulario.put("autor", jTextFieldAutor.getText());
        datosFormulario.put("eleccionEditorial", String.valueOf(jComboBoxEditoriales.getSelectedItem()));

        String eleccionEncuadernacion = null;
        if (buttonGroupEncuad.getSelection() != null) {
            eleccionEncuadernacion = buttonGroupEncuad.getSelection().getActionCommand();
        } else {
            eleccionEncuadernacion = "Por defecto";
        }
        datosFormulario.put("eleccionEncuadernacion", eleccionEncuadernacion);

        List<String> materias = new ArrayList<>();
        if (jCheckBoxTab11.isSelected()) materias.add(jCheckBoxTab11.getText());
        if (jCheckBoxTab12.isSelected()) materias.add(jCheckBoxTab12.getText());
        if (jCheckBoxTab13.isSelected()) materias.add(jCheckBoxTab13.getText());
        if (jCheckBoxTab21.isSelected()) materias.add(jCheckBoxTab21.getText());
        if (jCheckBoxTab22.isSelected()) materias.add(jCheckBoxTab22.getText());
        if (jCheckBoxTab23.isSelected()) materias.add(jCheckBoxTab23.getText());
        if (jCheckBoxTab31.isSelected()) materias.add(jCheckBoxTab31.getText());
        if (jCheckBoxTab32.isSelected()) materias.add(jCheckBoxTab32.getText());
        if (jCheckBoxTab33.isSelected()) materias.add(jCheckBoxTab33.getText());
        if (jCheckBoxTab41.isSelected()) materias.add(jCheckBoxTab41.getText());
        if (jCheckBoxTab42.isSelected()) materias.add(jCheckBoxTab42.getText());
        if (jCheckBoxTab43.isSelected()) materias.add(jCheckBoxTab43.getText());
        datosFormulario.put("materias", materias);

        datosFormulario.put("fechaPrestamo", jSpinnerFechaDevolucion.getValue());
        datosFormulario.put("fechaDevolucion", jSpinnerFechaPrestamo.getValue());

        return datosFormulario;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupEncuad;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JTabbedPane jCheckBoxTab;
    private javax.swing.JCheckBox jCheckBoxTab11;
    private javax.swing.JCheckBox jCheckBoxTab12;
    private javax.swing.JCheckBox jCheckBoxTab13;
    private javax.swing.JCheckBox jCheckBoxTab21;
    private javax.swing.JCheckBox jCheckBoxTab22;
    private javax.swing.JCheckBox jCheckBoxTab23;
    private javax.swing.JCheckBox jCheckBoxTab31;
    private javax.swing.JCheckBox jCheckBoxTab32;
    private javax.swing.JCheckBox jCheckBoxTab33;
    private javax.swing.JCheckBox jCheckBoxTab41;
    private javax.swing.JCheckBox jCheckBoxTab42;
    private javax.swing.JCheckBox jCheckBoxTab43;
    private javax.swing.JComboBox<String> jComboBoxEditoriales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private componentevisualpersonalizado.JPanelPersonalizado jPanelPersonalizado2;
    private javax.swing.JRadioButton jRadioButtonPiel;
    private javax.swing.JRadioButton jRadioButtonRustica;
    private javax.swing.JRadioButton jRadioButtonTapaDura;
    private javax.swing.JSpinner jSpinnerFechaDevolucion;
    private javax.swing.JSpinner jSpinnerFechaPrestamo;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldNomApell;
    private javax.swing.JTextField jTextFieldNumTelef;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables

}